### ISSUE TITLE
trying to create a new projects results in a null pointer exception

### ISSUE THREAD

**Issue by ardiehl** [TuononenP/pkg-config-support-for-eclipse-cdt#17]
when pkg-config is installed, trying to create a new projects results in a null pointer exception. Tried to crete an empty c++ project for gcc-linux in Fedora 24.

Exception:java.lang.NullPointerException: null
     at org.eclipse.cdt.managedbuilder.pkgconfig.Activator$1.handleEvent(Activator.java:90)
     at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.notifyListeners(CProjectDescriptionManager.java:2212)
     at org.eclipse.cdt.internal.core.settings.model.AbstractCProjectDescriptionStorage.fireDataAppliedEvent(AbstractCProjectDescriptionStorage.java:302)
     at org.eclipse.cdt.internal.core.settings.model.SetCProjectDescriptionOperation.executeOperation(SetCProjectDescriptionOperation.java:126)
     at org.eclipse.cdt.internal.core.model.CModelOperation.execute(CModelOperation.java:341)
     at org.eclipse.cdt.internal.core.model.CModelOperation.run(CModelOperation.java:607)
     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
     at org.eclipse.cdt.internal.core.model.CModelOperation.runOperation(CModelOperation.java:638)
     at org.eclipse.cdt.internal.core.settings.model.AbstractCProjectDescriptionStorage.setProjectDescription(AbstractCProjectDescriptionStorage.java:203)
     at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionStorageManager.setProjectDescription(CProjectDescriptionStorageManager.java:149)
     at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:885)
     at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:846)
     at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.setProjectDescription(CProjectDescriptionManager.java:840)
     at org.eclipse.cdt.managedbuilder.ui.wizards.MBSWizardHandler.setProjectDescription(MBSWizardHandler.java:620)
     at org.eclipse.cdt.managedbuilder.ui.wizards.MBSWizardHandler.createProject(MBSWizardHandler.java:558)
     at org.eclipse.cdt.ui.wizards.CDTCommonProjectWizard$1$1$1.run(CDTCommonProjectWizard.java:259)
     at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:67)
     at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:107)
     at org.eclipse.ui.actions.WorkspaceModifyOperation$$Lambda$128.0000000054024DA0.run(null:-1)
     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
     at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
     at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:128)
     at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
     at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
     at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:993)
     at org.eclipse.cdt.ui.wizards.CDTCommonProjectWizard$1$1.run(CDTCommonProjectWizard.java:268)
     at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
     at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4528)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4146)
     at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:165)
     at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:369)
     at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:993)
     at org.eclipse.cdt.ui.wizards.CDTCommonProjectWizard.invokeRunnable(CDTCommonProjectWizard.java:177)
     at org.eclipse.cdt.ui.wizards.CDTCommonProjectWizard.getProject(CDTCommonProjectWizard.java:155)
     at org.eclipse.cdt.ui.wizards.CDTCommonProjectWizard.performFinish(CDTCommonProjectWizard.java:193)
     at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)
     at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)
     at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
     at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4553)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4143)
     at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
     at org.eclipse.jface.window.Window.open(Window.java:794)
     at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:133)
     at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
     at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
     at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
     at org.eclipse.jface.action.ActionContributionItem$$Lambda$70.00000000A7DB50B0.handleEvent(null:-1)
     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4553)
     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4143)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
     at java.lang.reflect.Method.invoke(Method.java:508)
     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
     at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

---
## REPORT

anonymousId         9e87beb9-4cd4-4ff9-86c3-8272ab6e113b
name  
email  
comment             when pkg-config is installed, trying to create a new projects results in a null pointer exception. Tried to crete an empty c++ project for gcc-linux in Fedora 24.
eclipseBuildId      4.6.0.v20160819-1000
eclipseProduct      org.eclipse.platform.ide
javaRuntimeVersion  pxa6480sr3fp11-20160817_02 (SR3 FP11)
osgiWs              gtk
osgiOs              Linux
osgiOsVersion       4.7.4.fc24
osgiArch            x86_64
severity            UNKNOWN

---
## BUNDLES

name                org.eclipse.cdt.core
version             6.0.0.201607010959

name                org.eclipse.cdt
version             9.0.0.201607010959

name                org.eclipse.cdt.managedbuilder.pkgconfig
version             1.0.0.201511082105

name                org.eclipse.cdt.managedbuilder.ui
version             9.0.0.201607010959

name                org.eclipse.cdt.ui
version             6.0.0.201607010959

name                org.eclipse.core.databinding.observable
version             1.6.0.v20160819-1000

name                org.eclipse.core.databinding
version             1.6.0.v20160819-1000

name                org.eclipse.core.resources
version             3.11.0.v20160819-1000

name                org.eclipse.core.runtime
version             3.12.0.v20160819-1000

name                org.eclipse.e4.ui.workbench
version             1.4.0.v20160819-1000

name                org.eclipse.e4.ui.workbench.swt
version             0.14.0.v20160819-1000

name                org.eclipse.equinox.app
version             1.3.400.v20160819-1000

name                org.eclipse.equinox.launcher
version             1.3.200.v20160819-1000

name                org.eclipse.jface
version             3.12.0.v20160819-1000

name                org.eclipse.swt
version             3.105.0.v20160819-1000

name                org.eclipse.ui
version             3.108.0.v20160819-1000

name                org.eclipse.ui.ide.application
version             1.1.100.v20160819-1000

name                org.eclipse.ui.ide
version             3.12.0.v20160819-1000

**Comment by TuononenP** [comment]
Fixed this in the latest version I uploaded today in update site. Also fixed Eclipse marketplace installation. Tested with Eclipse Neon.
